spring:
  datasource:
    hikari:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${DB_URL}
    url: ${DB_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: ${SPRINGBOOT_PORT}
